package com.huaweicloud.sdk.iot.device.demo;

import com.huaweicloud.sdk.iot.device.IoTDevice;



/**
 * This code is generated by FreeMarker
 *
 */
public class DeviceMain
{

    public static void main(String args[]) throws InterruptedException {

       String serverUri = "ssl://iot-acc.cn-north-4.myhuaweicloud.com:8883";
       String deviceId;
       String secret;

       if (args.length < 2) {
           System.out.println("input: deviceId secret [serverUri]");
           return;
       }

       //从命令行获取设备参数
       deviceId = args[0];
       secret = args[1];

       if (args.length > 2) {
           serverUri = args[2];
       }

        //创建设备
        IoTDevice device = new IoTDevice(serverUri, deviceId, secret);

        <#list device.serviceTypeCapabilities as service>
        ${service.serviceType}Service ${service.serviceType}ServiceInstance = new ${service.serviceType}Service();
        device.addService("${service.serviceId}", ${service.serviceType}ServiceInstance);
        ${service.serviceType}ServiceInstance.enableAutoReport(10000);

        </#list>

        if (device.init() != 0) {
            return;
        }

    }


}